# Project information
site_name: Programmēšanas mācību materiāli
site_url: https://siic-lv.github.io/programmesana/
site_description: >-
  Mācību materiāli pamatskolas un vidusskolas programmēšanas skolotājiem.
# Repository
# repo_name: siic-lv/programmesana
repo_url: https://github.com/siic-lv/programmesana
# edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 SIIC

# Configuration
theme:
  name: material
  language: en

  # 404 page
  static_templates:
    - 404.html

  # Default values, taken from mkdocs_theme.yml
  features:
    - tabs
    #- instant
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo

# Plugins
plugins:
  - search
# - htmlproofer # checks outside URL validity, makes build super slow
#   - minify:
#       minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/siic-lv
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/siic

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: siic-lv
      repo: programmesana
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Ievads: index.md
  - Pamatskola:
    - pamatskola.md
    - pamatskola/4.klase.md
    - pamatskola/5.klase.md
    - pamatskola/6.klase.md
    - pamatskola/7.klase.md
    - pamatskola/8.klase.md
    - pamatskola/9.klase.md
  - Vidusskola:
    - vidusskola.md
    - vidusskola/projekti.md 
    - vidusskola/p1.md
    - vidusskola/p1/specifikacija.md
    - vidusskola/p1/lietotaji.md
    - vidusskola/p1/datu_apstrade.md
    - vidusskola/p2/vienibu_testi.md
  - Uzlabo materiālus: palidzet.md
  - Licenze: license.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML  
# Google Analytics
# google_analytics:
#   - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#   - auto